Добавляем рыбные данные и рендерим на их основе попап и карточки фильмов
htmlacademy-ecmascript/901777-cinemaddict-17 pull request #4
Opened 2022-05-18 18:58 UTC by Ticha888

В board-presenter.js на 8 строке подключается попап, если закомментить строку то поаплодировать отключается, чтобы посмотреть как рендеряться карточки.
А в movie-model.js задается количество карточек фильмов.

2022-05-19 09:58 UTC, NikolaiKotikov requested changes
Кажется ты не совсем разобрался, как связать данные о фильме и его комментарии

2022-05-19 09:58 UTC, NikolaiKotikov commented on src/mock/movie-mock.js
> +export const getmovieData = () =>  ({
getMovieData

2022-05-19 09:58 UTC, NikolaiKotikov commented on src/model/movie-model.js
> +    const activeComments = [];
Не совсем понял, что ты тут хочешь сделать, нужно возвращать комментарии по id для определённого фильма, а не для всех, либо у всех фильмов id менять на сами комментарии

2022-05-19 09:58 UTC, NikolaiKotikov commented on src/presenter/board-presenter.js
> +import NewPopupView from '../view/popup-view.js';
По критерию [Б27](https://up.htmlacademy.ru/ecmascript/17/criteries#b27 ) если файл назван `popup-view` то ты из него экспортируешь (а потом в другом модуле импортируешь) класс с таким же названием `PopupVuew`

2022-05-19 09:58 UTC, NikolaiKotikov commented on src/presenter/board-presenter.js
> +      render (new NewPopupView(this.movieModel.getMovies()[i],this.movieModel.getCommentsMovie()),document.body); //добвляем попап в рендер
Не нужно отображать попапы сразу для всех фильмов, попап должен создаваться только в момент открытия, для конкретной карточки фильма

2022-05-19 09:58 UTC, NikolaiKotikov commented on src/presenter/board-presenter.js
> +    for (let i=0; i<this.movieModel.getCommentsMovie().length; i++){
Я уже писал, что модель данных для комментариев выбрана неверная, то есть логика по отрисовке комментариев должна находиться внутри самого попапа

2022-05-19 09:58 UTC, NikolaiKotikov commented on src/view/popup-comments-view.js
> +const createfilmComment = (filmComment) => {
createFilmComment

2022-05-28 11:57 UTC, Ticha888 commented
В последнем комите https://github.com/htmlacademy-ecmascript/901777-cinemaddict-17/pull/4/commits/6a75685b4199f9283001a54f7c733b6e6dc81d08, вроде модель генерирует верно, но на выходе получаю комментарии в виде массива в котором каждой коммент это тоже массив с один элементом - объектом комментарий. Не подскажешь пожалуйста каким методом это лучше поправить?

2022-05-29 15:09 UTC, NikolaiKotikov approved these changes
Нормально, двигайся дальше

2022-05-29 15:09 UTC, NikolaiKotikov commented on src/model/movie-model.js
> +      const commentsDetail = movie.comments.map((id)=>this.getCommentsbyId(id));
Тут ты всё-таки мутируешь исходные данные, лучше так не делать, но прямых критериев по этому поводу нет, просто прими к сведению

2022-05-29 15:10 UTC, merged